### PR TITLE
Added some customisations to edition drop embed

### PR DESCRIPTION
**Pull request by pingrishabh**
- Added param to enable light/dark mode
- Added param to override name
- Added param to override description
- Added param to show/hide inventory tab
- Added param to show/hide wallet

### CODE REVIEW

**Comment by pingrishabh** [comment]
Light Mode            |  Dark Mode
:-------------------------:|:-------------------------:
   |

**Comment by adam-maj** [comment]
Hi @Cheesetouched, taking a look at this right now - just going to switch the target branch to a new one so we can make a build for this.

Looks awesome though :)

**Comment by adam-maj** [comment]
Here's the new PR @Cheesetouched: https://github.com/thirdweb-dev/widgets/pull/34

**Comment by pingrishabh** [comment]
@adam-maj  Sounds good! Should I send PRs to `ct/customize` directly from now onwards?

**Comment by BECryptoMedia** [comment]
How would I change the embed code to, for example, turn off the description ?
I can see that adding "primaryColor=yellow" at the end of the src="http..." string changes the button to yellow, thats cool.  But how do I turn off or override the description... is there a list somewhere of the parameters and their options for customising ?

**Pull request merged**
